artifacts_root: artifacts 

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/asharma-02/Text_summarizer/raw/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion